include('../../K8s_3-tier_webapp/api-golang/Tiltfile')
include('../../K8s_3-tier_webapp/api-node/Tiltfile')
include('../../K8s_3-tier_webapp/client-react/Tiltfile')
include('../../K8s_3-tier_webapp/load-generator-python/Tiltfile')